apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 018722c9-b856-42be-9031-09c5f7b52eb6
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/crosspostinginstagram/cloud-run-source-deploy/instagram-automation
    run.googleapis.com/build-name: projects/412412438508/locations/us-central1/builds/018722c9-b856-42be-9031-09c5f7b52eb6
    run.googleapis.com/build-source-location: gs://run-sources-crosspostinginstagram-us-central1/services/instagram-automation/1772620290.286666-2bc6b749447f48af950ae785e9ea2642.zip#1772620294297691
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 554.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '3'
    run.googleapis.com/operation-id: f3fc38b4-7b0d-40f5-a564-6fc844b8b291
    run.googleapis.com/urls: '["https://instagram-automation-412412438508.us-central1.run.app","https://instagram-automation-76kati656a-uc.a.run.app"]'
    serving.knative.dev/creator: 412412438508-compute@developer.gserviceaccount.com
    serving.knative.dev/lastModifier: roadsmoscow@gmail.com
  creationTimestamp: '2026-02-28T09:49:36.046462Z'
  generation: 26
  labels:
    cloud.googleapis.com/location: us-central1
  name: instagram-automation
  namespace: '412412438508'
  resourceVersion: AAZMMF3vgOU
  selfLink: /apis/serving.knative.dev/v1/namespaces/412412438508/services/instagram-automation
  uid: e9c0b176-1fab-42ae-a6a7-2380074872db
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 554.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: bhktwskcsy
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: NEXTAUTH_URL
          value: https://instagram-automation-412412438508.us-central1.run.app
        - name: AUTH_TRUST_HOST
          value: 'true'
        - name: AUTH_SECRET
          value: 5bdae9479fd0137ec108774b8b9cf566636d9cdae30c86a76abaa7e1b40b74bd
        - name: AUTH_GOOGLE_ID
          value: 412412438508-t5dm32ko2stn9no1d3p2nvm1g1a9j1v0.apps.googleusercontent.com
        - name: AUTH_GOOGLE_SECRET
          value: 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
        - name: OPENAI_API_KEY
          value: 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
        - name: RAPIDAPI_KEY
          value: a5540b9e3amsh037c0ff736afabdp13ee5ajsn981e3c178da3
        - name: CLOUDINARY_CLOUD_NAME
          value: dmue4mgal
        - name: CLOUDINARY_API_KEY
          value: '793219884859617'
        - name: CLOUDINARY_API_SECRET
          value: LI-phOqhRrj0riI7LjVf9Oqm-MI
        - name: POSTMYPOST_TOKEN
          value: asg_PweaW68b0jCI9z-MLr5F6P9hinop
        - name: FIREBASE_SERVICE_ACCOUNT_KEY
          value: |
            {
              "type": "service_account",
              "project_id": "crosspostinginstagram",
              "private_key_id": "d4615bf69351a48172f87bcdd7cef85aaf87d435",
              "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDnWTEW8QEdDaL1\nG30dfGj3aF9jDoQsDXlyHTRbYobK8rEldbykQ5WLuzE+mNJWk2aQ+RZwhsYFJ9Pa\nD9VmFAGcQQdaGEVvvasficxBzB2AQToKJYD3DhC/Nfsz56hhriXspx8Z5zpXU7vx\n73WxDWB5nMzQH/BzsS8m15ugw/anJuw9M/ClGRJ9jr4fbpAja3pBNEpyjFwjrQeJ\n6k9U6hR36HI0l/mXzqAzseH0ITcCTQMPp42GZb16FejllhgECuS6X2uY3XNlE9Wy\nuCFTlKrhGQ8P3qnwGK04m8rjCK+eVcFbd2zT5JqQtlwztTdV+Ms6HEqKARNKEU02\nge1mopXFAgMBAAECggEAIt9WL7nY298GGRHRcHwkG2UTecxCnpxSWeHuljbaECX4\nj2e5rX4VgPhQ0jl5fTzfSUuOtxwNpdHM1JIt7eLmoj3IJKvDbbZGoOylyiZBLSfH\n3qcsEzF+0z/JE5ggEMdOJqfDX6Vz7R1tV2jr0eotCG/bDKU/2sSS0bVO23Mmjyfc\nr/K2KViJBQA5b/j/BT1Dv1qAHQjbCFm5DgHpFI6Crfx8b6YmEN3UVUhyShvIgWMe\nb1NnF6jTODPH48lj792YDssjqJ06PlCUBoPviiD/IEitIDMPz4TuPjgXpJqWLNG+\nX9a6Qa7xcIyn2uPDS4/UW1H7J3lhB7Rxy3Ahs8oViQKBgQD5+ERtD7XX+Qo9mFk/\nhIZPg5au+yt5LJCLdBW5hXZC+YdCcjg7It1VY1eZqKpKRdIusaN2qLdH4RrUJ3RA\npxDOIzyrOFRA/xTlJqakY5iA8zYDkAG6gJJtsn8gsn4rFc8NFY0s1BKwTzTBS6nc\nUyNDjn5JIJWnIUBMNwr9wkm5fQKBgQDs7ey+rEVv7Qed2dk2rKlEQAq7nlQNAyD7\nuEFOVVX41N7YuQ/nOC7Tq55WdJn6LMGhvSG+Z/s1GlaJTz6YALcM19NRtdrc2sHH\nnqSxOWLV9BXkFKhV7kO53hGuRcJFeTgvgzFqF78fwy9bGr4RbP0JzRpCIjnXjwd5\nv4rpjd8/6QKBgAhkJSfkFx6g5Y8bxiMzt66DpFNLazIuJMwJoZEQwd+NsNSyMOEL\nUpLDOvWVi+HiZiPbIrmhAEYRcG0exfBFq3LADBFTWsCzz2fB3GY4Ua5Ce9Wyx9wS\n5Nd53nqig0m++axexNZ0aAwzHHpAp/sVb2GdLvAVf/CUVSw5zMyn8QGhAoGAQHdc\ne2UUX6f28pRb7ex9Af0K7pHd/MxlJRi1bEL76YDCQeXY1ekLlLyVkKCZZODYrtFv\nZQeV6pUIBsRxG5rWM8Bl103MB1vebhpUZYRfyCdp7W1RgFAcTW6HEQwaGB0rlIH1\n6BAeCN5q/DcCkGs/TnNoOaZmZqicOBxOB856eEECgYAzgGFBAg8vJkgjaT3V//3l\nPbmnH4mkB1f5y2Atd4wSeq/b0OVgex7nbUrIFtnTXzmRV968+Sk08qXbjojE+F83\nnWYbljds3QUgS0qluBR42VCVOSYD0aE2sP2sEjOWwVusVlCiTavs3scfZMkLRUkV\nAxdzH73VwMNXEtsQK1vZCQ==\n-----END PRIVATE KEY-----\n",
              "client_email": "instagram-bot42@crosspostinginstagram.iam.gserviceaccount.com",
              "client_id": "100005373442200068133",
              "auth_uri": "https://accounts.google.com/o/oauth2/auth",
              "token_uri": "https://oauth2.googleapis.com/token",
              "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
              "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/instagram-bot42%40crosspostinginstagram.iam.gserviceaccount.com",
              "universe_domain": "googleapis.com"
            }
        - name: AUTH_URL
          value: https://instagram-automation-412412438508.us-central1.run.app
        - name: TELEGRAM_BOT_TOKEN
          value: 8418236788:AAFlETXa0c4ORhlEfGdjVPvMrxl7-b2liTM
        image: us-central1-docker.pkg.dev/crosspostinginstagram/cloud-run-source-deploy/instagram-automation@sha256:ff66fb3ace9daa0eb82e8d348dd20b1cb3bd1684406b57475d1c194b60d66647
        ports:
        - containerPort: 3000
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 3000
          timeoutSeconds: 240
      serviceAccountName: 412412438508-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://instagram-automation-76kati656a-uc.a.run.app
  conditions:
  - lastTransitionTime: '2026-03-04T10:34:38.382309Z'
    status: 'True'
    type: Ready
  - lastTransitionTime: '2026-03-04T10:34:37.133852Z'
    status: 'True'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-03-04T10:34:38.347826Z'
    status: 'True'
    type: RoutesReady
  latestCreatedRevisionName: instagram-automation-00026-fmd
  latestReadyRevisionName: instagram-automation-00026-fmd
  observedGeneration: 26
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: instagram-automation-00026-fmd
  url: https://instagram-automation-76kati656a-uc.a.run.app
